### ISSUE TITLE
Plan with changes on terraform 0.15 do not display anything

### ISSUE THREAD

**Issue by ADefossez-Zenika** [robburger/terraform-pr-commenter#9]
https://github.com/robburger/terraform-pr-commenter/blob/c4553968e1959190073eb056c9fc8a6582cb06b7/entrypoint.sh#L186

Hello, i've upgraded my terraform to 0.15, and it seems that i can't see my changes, because the sentence has changed, on terraform's side.

ex on 0.15 :

```
Terraform used the selected providers to generate the following execution
plan. Resource actions are indicated with the following symbols:
  ~ update in-place

Terraform will perform the following actions:
```

VS on 0.13, for example : 
```
An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
  ~ update in-place

Terraform will perform the following actions:
```
We can see the "An execution plan has been generated and is shown below." has disappear.

Maybe we can fix the regex to catch both sentences ?

**Comment by robburger** [comment]
Thanks @ADefossez-Zenika - I'm having a look at your PR now

**Comment by robburger** [comment]
@ADefossez-Zenika thanks for the contribution - changes merged in! I'll create a release now and move the `v1` tag 🙌
